env:
  global:
    - CODECOV_TOKEN="fea8f0d7-c4a5-492b-a3a7-3585495d633d"

language: go

go:
- 1.9 
- tip

before_install:
  - go get -t -v ./...

script:
  - go test ./bold
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
